services:

  app:
    build: .
    container_name: ragil_be
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    networks:
      - postgres_network

networks:
  postgres_network:
    external: true
